import { fromEvent } from 'rxjs';
import { map, tap } from 'rxjs/operators'


const texto = document.createElement( 'div' );
texto.innerHTML = `
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ligula ante, malesuada sed nisl vitae, auctor suscipit mauris. Maecenas tincidunt pretium blandit. Pellentesque maximus lacinia eros maximus faucibus. Integer non dignissim justo. Pellentesque eu pretium magna, eget vulputate nisl. Fusce felis odio, fringilla quis suscipit vitae, egestas sit amet magna. Vestibulum pellentesque elementum dapibus. Nunc tristique sit amet nisl in rutrum.
    <br/></br>
    Integer dapibus, eros ut congue luctus, metus augue consectetur nisl, eget volutpat sapien metus id erat. Mauris sit amet lorem in leo congue fermentum. Proin et scelerisque nisl. Nullam mi urna, consectetur sed risus lobortis, eleifend laoreet massa. Donec ex velit, facilisis sed turpis nec, lobortis tempus arcu. Aliquam eget dignissim lacus, quis interdum dolor. Morbi ornare eu massa ut interdum. Phasellus sit amet turpis in ante finibus efficitur. Phasellus feugiat risus nibh, aliquam tempus nibh placerat eget. Phasellus rutrum ut mauris et iaculis. Etiam aliquet mauris at tortor imperdiet semper. Curabitur vulputate venenatis elit at iaculis. Proin pellentesque, ligula at accumsan mollis, enim nunc posuere turpis, id sagittis justo justo quis erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    <br/></br>
    Donec sit amet ornare justo, ut vestibulum quam. Integer dignissim feugiat odio, iaculis pulvinar dui tempor sed. Nunc tincidunt massa ante, quis viverra diam laoreet quis. Aliquam a tellus ante. Quisque aliquet sapien dignissim pretium eleifend. Vivamus in aliquam mauris. Vivamus blandit commodo dui, vitae accumsan leo finibus ut. Vestibulum sed lectus lacinia, volutpat justo eu, molestie justo. Fusce at nibh ac diam ultricies fringilla. Cras at porta est, sit amet elementum dolor. Aenean a lacinia lectus, vel faucibus metus. Proin lobortis commodo consectetur. Suspendisse efficitur enim felis, non tincidunt quam volutpat in.
    <br/></br>
    Maecenas quis diam et nunc mattis dapibus. Pellentesque elit odio, feugiat eget nunc et, lacinia feugiat velit. Aliquam sagittis, justo quis porta ultricies, tellus orci laoreet felis, sit amet porta nisl ante a orci. Morbi ultrices aliquam turpis eget finibus. Morbi at pellentesque diam. Donec tortor dolor, aliquet laoreet sollicitudin at, gravida vel erat. Praesent elementum diam id nisl porttitor, accumsan vehicula ante consequat.
    <br/></br>
    Ut augue eros, venenatis sed facilisis quis, ultrices nec mi. Aliquam a libero eget libero iaculis lacinia. Praesent eget ante vitae magna fringilla rhoncus. Fusce leo sapien, aliquet tincidunt est non, aliquam maximus ipsum. Nulla lobortis vitae diam ut egestas. Sed nunc urna, faucibus ut nisi in, placerat convallis lacus. Vivamus luctus, leo a mollis ornare, arcu est viverra augue, nec mattis metus sem non lacus. In id iaculis sem, ut maximus erat. Vivamus sed odio vitae odio pellentesque imperdiet. Nam non suscipit mauris. Cras in augue maximus, cursus ante volutpat, dictum leo. Donec gravida, urna nec mollis malesuada, diam nunc dapibus magna, vitae malesuada magna nibh id urna. Vivamus tempus magna sed ante pretium porta. Mauris porta auctor ex sit amet porta.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ligula ante, malesuada sed nisl vitae, auctor suscipit mauris. Maecenas tincidunt pretium blandit. Pellentesque maximus lacinia eros maximus faucibus. Integer non dignissim justo. Pellentesque eu pretium magna, eget vulputate nisl. Fusce felis odio, fringilla quis suscipit vitae, egestas sit amet magna. Vestibulum pellentesque elementum dapibus. Nunc tristique sit amet nisl in rutrum.
    <br/></br>
    Integer dapibus, eros ut congue luctus, metus augue consectetur nisl, eget volutpat sapien metus id erat. Mauris sit amet lorem in leo congue fermentum. Proin et scelerisque nisl. Nullam mi urna, consectetur sed risus lobortis, eleifend laoreet massa. Donec ex velit, facilisis sed turpis nec, lobortis tempus arcu. Aliquam eget dignissim lacus, quis interdum dolor. Morbi ornare eu massa ut interdum. Phasellus sit amet turpis in ante finibus efficitur. Phasellus feugiat risus nibh, aliquam tempus nibh placerat eget. Phasellus rutrum ut mauris et iaculis. Etiam aliquet mauris at tortor imperdiet semper. Curabitur vulputate venenatis elit at iaculis. Proin pellentesque, ligula at accumsan mollis, enim nunc posuere turpis, id sagittis justo justo quis erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    <br/></br>
    Donec sit amet ornare justo, ut vestibulum quam. Integer dignissim feugiat odio, iaculis pulvinar dui tempor sed. Nunc tincidunt massa ante, quis viverra diam laoreet quis. Aliquam a tellus ante. Quisque aliquet sapien dignissim pretium eleifend. Vivamus in aliquam mauris. Vivamus blandit commodo dui, vitae accumsan leo finibus ut. Vestibulum sed lectus lacinia, volutpat justo eu, molestie justo. Fusce at nibh ac diam ultricies fringilla. Cras at porta est, sit amet elementum dolor. Aenean a lacinia lectus, vel faucibus metus. Proin lobortis commodo consectetur. Suspendisse efficitur enim felis, non tincidunt quam volutpat in.
    <br/></br>
    Maecenas quis diam et nunc mattis dapibus. Pellentesque elit odio, feugiat eget nunc et, lacinia feugiat velit. Aliquam sagittis, justo quis porta ultricies, tellus orci laoreet felis, sit amet porta nisl ante a orci. Morbi ultrices aliquam turpis eget finibus. Morbi at pellentesque diam. Donec tortor dolor, aliquet laoreet sollicitudin at, gravida vel erat. Praesent elementum diam id nisl porttitor, accumsan vehicula ante consequat.
    <br/></br>
    Ut augue eros, venenatis sed facilisis quis, ultrices nec mi. Aliquam a libero eget libero iaculis lacinia. Praesent eget ante vitae magna fringilla rhoncus. Fusce leo sapien, aliquet tincidunt est non, aliquam maximus ipsum. Nulla lobortis vitae diam ut egestas. Sed nunc urna, faucibus ut nisi in, placerat convallis lacus. Vivamus luctus, leo a mollis ornare, arcu est viverra augue, nec mattis metus sem non lacus. In id iaculis sem, ut maximus erat. Vivamus sed odio vitae odio pellentesque imperdiet. Nam non suscipit mauris. Cras in augue maximus, cursus ante volutpat, dictum leo. Donec gravida, urna nec mollis malesuada, diam nunc dapibus magna, vitae malesuada magna nibh id urna. Vivamus tempus magna sed ante pretium porta. Mauris porta auctor ex sit amet porta.        
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ligula ante, malesuada sed nisl vitae, auctor suscipit mauris. Maecenas tincidunt pretium blandit. Pellentesque maximus lacinia eros maximus faucibus. Integer non dignissim justo. Pellentesque eu pretium magna, eget vulputate nisl. Fusce felis odio, fringilla quis suscipit vitae, egestas sit amet magna. Vestibulum pellentesque elementum dapibus. Nunc tristique sit amet nisl in rutrum.
    <br/></br>
    Integer dapibus, eros ut congue luctus, metus augue consectetur nisl, eget volutpat sapien metus id erat. Mauris sit amet lorem in leo congue fermentum. Proin et scelerisque nisl. Nullam mi urna, consectetur sed risus lobortis, eleifend laoreet massa. Donec ex velit, facilisis sed turpis nec, lobortis tempus arcu. Aliquam eget dignissim lacus, quis interdum dolor. Morbi ornare eu massa ut interdum. Phasellus sit amet turpis in ante finibus efficitur. Phasellus feugiat risus nibh, aliquam tempus nibh placerat eget. Phasellus rutrum ut mauris et iaculis. Etiam aliquet mauris at tortor imperdiet semper. Curabitur vulputate venenatis elit at iaculis. Proin pellentesque, ligula at accumsan mollis, enim nunc posuere turpis, id sagittis justo justo quis erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    <br/></br>
    Donec sit amet ornare justo, ut vestibulum quam. Integer dignissim feugiat odio, iaculis pulvinar dui tempor sed. Nunc tincidunt massa ante, quis viverra diam laoreet quis. Aliquam a tellus ante. Quisque aliquet sapien dignissim pretium eleifend. Vivamus in aliquam mauris. Vivamus blandit commodo dui, vitae accumsan leo finibus ut. Vestibulum sed lectus lacinia, volutpat justo eu, molestie justo. Fusce at nibh ac diam ultricies fringilla. Cras at porta est, sit amet elementum dolor. Aenean a lacinia lectus, vel faucibus metus. Proin lobortis commodo consectetur. Suspendisse efficitur enim felis, non tincidunt quam volutpat in.
    <br/></br>
    Maecenas quis diam et nunc mattis dapibus. Pellentesque elit odio, feugiat eget nunc et, lacinia feugiat velit. Aliquam sagittis, justo quis porta ultricies, tellus orci laoreet felis, sit amet porta nisl ante a orci. Morbi ultrices aliquam turpis eget finibus. Morbi at pellentesque diam. Donec tortor dolor, aliquet laoreet sollicitudin at, gravida vel erat. Praesent elementum diam id nisl porttitor, accumsan vehicula ante consequat.
    <br/></br>
    Ut augue eros, venenatis sed facilisis quis, ultrices nec mi. Aliquam a libero eget libero iaculis lacinia. Praesent eget ante vitae magna fringilla rhoncus. Fusce leo sapien, aliquet tincidunt est non, aliquam maximus ipsum. Nulla lobortis vitae diam ut egestas. Sed nunc urna, faucibus ut nisi in, placerat convallis lacus. Vivamus luctus, leo a mollis ornare, arcu est viverra augue, nec mattis metus sem non lacus. In id iaculis sem, ut maximus erat. Vivamus sed odio vitae odio pellentesque imperdiet. Nam non suscipit mauris. Cras in augue maximus, cursus ante volutpat, dictum leo. Donec gravida, urna nec mollis malesuada, diam nunc dapibus magna, vitae malesuada magna nibh id urna. Vivamus tempus magna sed ante pretium porta. Mauris porta auctor ex sit amet porta.    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ligula ante, malesuada sed nisl vitae, auctor suscipit mauris. Maecenas tincidunt pretium blandit. Pellentesque maximus lacinia eros maximus faucibus. Integer non dignissim justo. Pellentesque eu pretium magna, eget vulputate nisl. Fusce felis odio, fringilla quis suscipit vitae, egestas sit amet magna. Vestibulum pellentesque elementum dapibus. Nunc tristique sit amet nisl in rutrum.
    <br/></br>
    Integer dapibus, eros ut congue luctus, metus augue consectetur nisl, eget volutpat sapien metus id erat. Mauris sit amet lorem in leo congue fermentum. Proin et scelerisque nisl. Nullam mi urna, consectetur sed risus lobortis, eleifend laoreet massa. Donec ex velit, facilisis sed turpis nec, lobortis tempus arcu. Aliquam eget dignissim lacus, quis interdum dolor. Morbi ornare eu massa ut interdum. Phasellus sit amet turpis in ante finibus efficitur. Phasellus feugiat risus nibh, aliquam tempus nibh placerat eget. Phasellus rutrum ut mauris et iaculis. Etiam aliquet mauris at tortor imperdiet semper. Curabitur vulputate venenatis elit at iaculis. Proin pellentesque, ligula at accumsan mollis, enim nunc posuere turpis, id sagittis justo justo quis erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    <br/></br>
    Donec sit amet ornare justo, ut vestibulum quam. Integer dignissim feugiat odio, iaculis pulvinar dui tempor sed. Nunc tincidunt massa ante, quis viverra diam laoreet quis. Aliquam a tellus ante. Quisque aliquet sapien dignissim pretium eleifend. Vivamus in aliquam mauris. Vivamus blandit commodo dui, vitae accumsan leo finibus ut. Vestibulum sed lectus lacinia, volutpat justo eu, molestie justo. Fusce at nibh ac diam ultricies fringilla. Cras at porta est, sit amet elementum dolor. Aenean a lacinia lectus, vel faucibus metus. Proin lobortis commodo consectetur. Suspendisse efficitur enim felis, non tincidunt quam volutpat in.
    <br/></br>
    Maecenas quis diam et nunc mattis dapibus. Pellentesque elit odio, feugiat eget nunc et, lacinia feugiat velit. Aliquam sagittis, justo quis porta ultricies, tellus orci laoreet felis, sit amet porta nisl ante a orci. Morbi ultrices aliquam turpis eget finibus. Morbi at pellentesque diam. Donec tortor dolor, aliquet laoreet sollicitudin at, gravida vel erat. Praesent elementum diam id nisl porttitor, accumsan vehicula ante consequat.
    <br/></br>
    Ut augue eros, venenatis sed facilisis quis, ultrices nec mi. Aliquam a libero eget libero iaculis lacinia. Praesent eget ante vitae magna fringilla rhoncus. Fusce leo sapien, aliquet tincidunt est non, aliquam maximus ipsum. Nulla lobortis vitae diam ut egestas. Sed nunc urna, faucibus ut nisi in, placerat convallis lacus. Vivamus luctus, leo a mollis ornare, arcu est viverra augue, nec mattis metus sem non lacus. In id iaculis sem, ut maximus erat. Vivamus sed odio vitae odio pellentesque imperdiet. Nam non suscipit mauris. Cras in augue maximus, cursus ante volutpat, dictum leo. Donec gravida, urna nec mollis malesuada, diam nunc dapibus magna, vitae malesuada magna nibh id urna. Vivamus tempus magna sed ante pretium porta. Mauris porta auctor ex sit amet porta.    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ligula ante, malesuada sed nisl vitae, auctor suscipit mauris. Maecenas tincidunt pretium blandit. Pellentesque maximus lacinia eros maximus faucibus. Integer non dignissim justo. Pellentesque eu pretium magna, eget vulputate nisl. Fusce felis odio, fringilla quis suscipit vitae, egestas sit amet magna. Vestibulum pellentesque elementum dapibus. Nunc tristique sit amet nisl in rutrum.
    <br/></br>
    Integer dapibus, eros ut congue luctus, metus augue consectetur nisl, eget volutpat sapien metus id erat. Mauris sit amet lorem in leo congue fermentum. Proin et scelerisque nisl. Nullam mi urna, consectetur sed risus lobortis, eleifend laoreet massa. Donec ex velit, facilisis sed turpis nec, lobortis tempus arcu. Aliquam eget dignissim lacus, quis interdum dolor. Morbi ornare eu massa ut interdum. Phasellus sit amet turpis in ante finibus efficitur. Phasellus feugiat risus nibh, aliquam tempus nibh placerat eget. Phasellus rutrum ut mauris et iaculis. Etiam aliquet mauris at tortor imperdiet semper. Curabitur vulputate venenatis elit at iaculis. Proin pellentesque, ligula at accumsan mollis, enim nunc posuere turpis, id sagittis justo justo quis erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    <br/></br>
    Donec sit amet ornare justo, ut vestibulum quam. Integer dignissim feugiat odio, iaculis pulvinar dui tempor sed. Nunc tincidunt massa ante, quis viverra diam laoreet quis. Aliquam a tellus ante. Quisque aliquet sapien dignissim pretium eleifend. Vivamus in aliquam mauris. Vivamus blandit commodo dui, vitae accumsan leo finibus ut. Vestibulum sed lectus lacinia, volutpat justo eu, molestie justo. Fusce at nibh ac diam ultricies fringilla. Cras at porta est, sit amet elementum dolor. Aenean a lacinia lectus, vel faucibus metus. Proin lobortis commodo consectetur. Suspendisse efficitur enim felis, non tincidunt quam volutpat in.
    <br/></br>
    Maecenas quis diam et nunc mattis dapibus. Pellentesque elit odio, feugiat eget nunc et, lacinia feugiat velit. Aliquam sagittis, justo quis porta ultricies, tellus orci laoreet felis, sit amet porta nisl ante a orci. Morbi ultrices aliquam turpis eget finibus. Morbi at pellentesque diam. Donec tortor dolor, aliquet laoreet sollicitudin at, gravida vel erat. Praesent elementum diam id nisl porttitor, accumsan vehicula ante consequat.
    <br/></br>
    Ut augue eros, venenatis sed facilisis quis, ultrices nec mi. Aliquam a libero eget libero iaculis lacinia. Praesent eget ante vitae magna fringilla rhoncus. Fusce leo sapien, aliquet tincidunt est non, aliquam maximus ipsum. Nulla lobortis vitae diam ut egestas. Sed nunc urna, faucibus ut nisi in, placerat convallis lacus. Vivamus luctus, leo a mollis ornare, arcu est viverra augue, nec mattis metus sem non lacus. In id iaculis sem, ut maximus erat. Vivamus sed odio vitae odio pellentesque imperdiet. Nam non suscipit mauris. Cras in augue maximus, cursus ante volutpat, dictum leo. Donec gravida, urna nec mollis malesuada, diam nunc dapibus magna, vitae malesuada magna nibh id urna. Vivamus tempus magna sed ante pretium porta. Mauris porta auctor ex sit amet porta.                
`;

const body = document.querySelector( 'body' );
body.append( texto );

const progressBar = document.createElement( 'div' );
progressBar.setAttribute( 'class', 'progress-bar' );
body.append( progressBar );

// Función que haga el cálculo
const calcularPorcentajeScroll = ( event ) => {

    const { scrollTop, scrollHeight, clientHeight } = event.target.documentElement;
    return 100 * scrollTop / ( scrollHeight - clientHeight );

}

// Streams
const scroll$ = fromEvent( document, 'scroll' );

const progress$ = scroll$.pipe(
    map( calcularPorcentajeScroll ),
    tap( console.log ),
);

progress$.subscribe( porcentaje => {    
    progressBar.style.width = `${ porcentaje }%`;

});
